### ISSUE TITLE
Support statements with bound values

### ISSUE THREAD

**Issue by sam701** [perdumonocle/sql-builder#1]
Hi,

first, thank you for this great crate!

It would be nice to have support for bound values, i.e. statements with `?` or `$1`. So it would benefit from DB statement caching.

**Comment by perdumonocle** [comment]
Like this?

```rust
let sql = SqlBuilder::select_from("books")
    .field("title")
    .field("price")
    .and_where("price > ?")
    .and_where("title LIKE ?")
    .bind(100)
    .bind("Harry Potter%")
    .sql()?;
```

**Comment by sam701** [comment]
Yes, or even like this
```rust
let sql = SqlBuilder::select_from("books")
    .field("title")
    .field("price")
    .and_where("price > ?", 100)
    .and_where("title LIKE ?", "Harry Potter%")
    .sql()?;
```

`?` can be replaced by `$1` if dialect is postgres.

Such form would be extremely helpful for example when you create the SQL statement based on multiple search criteria. I.e. in a web server processing a search query: if the user submitted this use  `where(a)`, if the user submitted that add `where(b)`.

These ideas are taken from [squirrel](https://github.com/Masterminds/squirrel).

**Comment by perdumonocle** [comment]
But Rust has no function overloading. I can make separate macro for that:

```rust
.and_where( bind!("price BETWEEN ? AND ?", 100, 200) )
```

**Comment by sam701** [comment]
Maybe it can be something like this
```rust
fn and_where<T: TypeTrait>(sql: &str, bindings: &[T]) {...}
```

And the final `sql()` could return a tuple of SQL statement and `Vec<dyn TypeTrait>`

**Comment by perdumonocle** [comment]
Check, please:

```rust
let sql = SqlBuilder::select_from("company")
    .fields(&["id", "name"])
    .and_where("salary BETWEEN ? AND ?".binds(&[&10000, &25000]))
    .and_where("staff BETWEEN ? AND ?".bind(&100).bind(&200))
    .sql()?;
```

**Comment by sam701** [comment]
I like usage of `bind/binds` 👍 But I guess in order to be able to benefit from SQL statement caching, `sql()?` should return two things (they can be wrapped in a struct):
* SQL statement *with* `?`/`$1`
* a list of variables to bind

Having things like this, would allow a DB server to cache the execution plan for the statements with `?` and reuse it for any different incoming variables.

**Comment by perdumonocle** [comment]
May it will be convenient in this form?

```rust
let statement = SqlBuilder::select_from("books")
    .field("title")
    .and_where("price > ?")
    .and_where("title LIKE ?")
    .prepare()?;

let sql1 = statement.sql(&[&100, &"Harry%"])?; // SELECT title FROM books WHERE price > 100 AND title LIKE 'Harry%';
let sql2 = statement.sql(&[&200, &"Alice%"])?; // SELECT title FROM books WHERE price > 200 AND title LIKE 'Alice%';
```

**Comment by sam701** [comment]
Actually I like more the previous variant
```rust
.and_where("salary BETWEEN ? AND ?".binds(&[&10000, &25000]))
```

It is helpful, because when you create the SQL for a search request from a user, it might contain multiple search criteria. So you can immediately provide required values:
```
if(criteria1) {
  sql_builder.and_where("salary BETWEEN ? AND ?".binds(&[&10000, &25000]))
}
if(criteria2) {
  sql_builder.join("tableX as X on X.id=Y.x_id")
}

let (sql, values) = sql_builder.sql()?;

my_transaction.execute(sql, values.into())?;
```

I guess the last proposal
```rust
let sql1 = statement.sql(&[&100, &"Harry%"])?;
let sql2 = statement.sql(&[&200, &"Alice%"])?;
```
is not very helpful, because you again have the final statement as a string. So the DB server will have to generate (actually the same) plan for `sql1` and `sql2`.

**Comment by perdumonocle** [comment]
Since 0.11.9:

bind, binds:
```rust
"staff BETWEEN ? AND ?".bind(&100).bind(&200))

"salary BETWEEN ? AND ?".binds(&[&10_000, &25_000]))
```

bind_num, bind_nums:
```rust
"staff BETWEEN $1 AND $2".bind_num(1, &100).bind_num(2, &200))

"salary BETWEEN $1 AND $2".bind_nums(&[&10_000, &25_000]))
```

bind_name, bind_names:
```rust
"staff BETWEEN :min: AND :max:".bind_name("min", &100.sql_arg()).bind_name("max", &200.sql_arg()))

let mut names = HashMap::new();
names.insert("min", 1_000_i32.sql_arg());
names.insert("max", 25_000_i32.sql_arg());
"salary BETWEEN :min: AND :max:".bind_names(&names)
```

**Comment by sam701** [comment]
How would you use it with for example [sqlx](https://github.com/launchbadge/sqlx)?
